<?php

namespace App\Actions;

use App\Enums\ReservationSource;
use App\Enums\ReservationStatus;
use App\Models\Item;
use App\Models\Reservation;
use App\Models\User;

/**
 * Single-purpose atomic action: persist a new Reservation row.
 *
 * Pre-conditions (validated by ReservationService before calling):
 *  - Slot is available (no overlapping active reservations)
 *  - party_size <= item.capacity
 *  - item is active and reservable
 *  - price_snapshot and discount data already resolved
 *
 * The confirmation_code is generated by ReservationObserver::creating().
 */
final class CreateReservationAction
{
    public function execute(
        User  $user,
        Item  $item,
        array $validated,
        array $priceData,     // ['total_amount', 'discount_amount', 'price_snapshot', 'promo_snapshot', 'applied_promo_id']
    ): Reservation {
        return Reservation::create([
            'user_id'          => $user->id,
            'item_id'          => $item->id,
            'business_id'      => $item->business_id,
            'status'           => ReservationStatus::Pending,
            'source'           => ReservationSource::from($validated['source'] ?? ReservationSource::App->value),
            'scheduled_date'   => $validated['scheduled_date'],
            'start_time'       => $validated['start_time'],
            'duration_minutes' => $validated['duration_minutes'] ?? $item->duration_minutes,
            'party_size'       => $validated['party_size'],
            'notes'            => $validated['notes'] ?? null,
            'total_amount'     => $priceData['total_amount'],
            'discount_amount'  => $priceData['discount_amount'],
            'applied_promo_id' => $priceData['applied_promo_id'] ?? null,
            'price_snapshot'   => $priceData['price_snapshot'],
            'promo_snapshot'   => $priceData['promo_snapshot'] ?? null,
            // confirmation_code set by ReservationObserver::creating()
        ]);
    }
}
