<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Reservations — the core transactional entity.
 *
 * Design decisions:
 * - Anti double-booking is a two-layer guarantee:
 *     1. DB: unique index on [item_id, scheduled_date, start_time] catches exact-slot
 *        collisions at the database level (fast, zero-latency guard).
 *     2. Code: ReservationService uses lockForUpdate() inside a transaction to detect
 *        overlapping durations that the unique index cannot catch.
 * - `duration_minutes` is stored on the reservation (not derived from items) because
 *   the item's default duration can change over time.
 * - `price_snapshot` JSON stores the effective item price at booking time; used for
 *   invoicing and never re-derived from items.price after creation (immutable).
 * - `promo_snapshot` JSON stores the full promotion config that was applied, so future
 *   changes to the promotion row don't alter historical discount values.
 * - `discount_amount` centavos — redundantly stored beside promo_snapshot for fast
 *   aggregation queries without JSON parsing.
 * - `total_amount` = sum of (item price + pre-order items) - discount_amount, centavos.
 * - `confirmation_code` 8-char uppercase alphanumeric — generated by ReservationObserver.
 * - Event timestamps (confirmed_at, cancelled_at, completed_at) are explicit nullable
 *   columns, not derived from status updates, for reliable business-event analytics.
 * - FK to users is restrictOnDelete — reservations are historical records; user soft-
 *   delete is the intended deletion path for users who want data erasure.
 * - No softDeletes: reservations are immutable historical records; status = cancelled is
 *   the correct "delete" operation.
 * - Composite index [business_id, scheduled_date, status] covers the main dashboard query.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('reservations', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->foreignUlid('user_id')->constrained('users')->restrictOnDelete();
            $table->foreignUlid('item_id')->constrained('items')->restrictOnDelete();
            $table->foreignUlid('business_id')->constrained('businesses')->restrictOnDelete();
            $table->string('confirmation_code', 8)->unique();     // e.g. A3K9ZQ7M
            $table->string('status')->default('pending');          // ReservationStatus enum
            $table->string('source')->default('app');              // ReservationSource enum
            $table->date('scheduled_date');
            $table->time('start_time');
            $table->unsignedSmallInteger('duration_minutes');
            $table->unsignedSmallInteger('party_size')->default(1);
            $table->text('notes')->nullable();                     // special requests, allergies
            $table->unsignedBigInteger('total_amount');            // centavos
            $table->unsignedBigInteger('discount_amount')->default(0); // centavos
            $table->json('price_snapshot');                        // immutable item price at booking
            $table->json('promo_snapshot')->nullable();            // immutable promo config if applied
            // nullable FK to promotions — nullOnDelete keeps history when promo is soft-deleted
            $table->foreignUlid('applied_promo_id')
                  ->nullable()
                  ->constrained('promotions')
                  ->nullOnDelete();
            $table->timestamp('confirmed_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();
            $table->timestamp('completed_at')->nullable();
            $table->timestamps();

            // Layer 1 of anti double-booking: exact-slot unique constraint
            $table->unique(['item_id', 'scheduled_date', 'start_time'], 'reservations_slot_unique');

            $table->index('status');
            $table->index('user_id');
            $table->index('business_id');
            $table->index('scheduled_date');
            $table->index('source');
            $table->index(['business_id', 'scheduled_date', 'status']); // dashboard main query
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('reservations');
    }
};
